### ISSUE TITLE
server statefulset readiness cause pod start failed

### ISSUE THREAD

**Issue by like-inspur** [hashicorp/consul-helm#404] opened 2020-03-31 12:32 UTC
I use readiness config in server statefulset with consul image version 1.7.1 like this:
```
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - |
              curl http://127.0.0.1:8500/v1/status/leader \
              2>/dev/null | grep -E '".+"'
          initialDelaySeconds: 120
          periodSeconds: 120
          timeoutSeconds: 30
```
But server statefulset pod start failed, and always outputs error like this:
```
    2020/03/31 07:42:10 [INFO] agent: (LAN) joining: [consul-0.consul-svc consul-1.consul-svc consul-2.consul-svc]
    2020/03/31 07:42:10 [WARN] memberlist: Failed to resolve consul-0.consul-svc: lookup consul-0.consul-svc on 100.105.0.3:53: server misbehaving
    2020/03/31 07:42:10 [WARN] memberlist: Failed to resolve consul-1.consul-svc: lookup consul-1.consul-svc on 100.105.0.3:53: server misbehaving
    2020/03/31 07:42:10 [WARN] memberlist: Failed to resolve consul-2.consul-svc: lookup consul-2.consul-svc on 100.105.0.3:53: server misbehaving
    2020/03/31 07:42:10 [WARN] agent: (LAN) couldn't join: 0 Err: 3 errors occurred:
	* Failed to resolve consul-0.consul-svc: lookup consul-0.consul-svc on 100.105.0.3:53: server misbehaving
	* Failed to resolve consul-1.consul-svc: lookup consul-1.consul-svc on 100.105.0.3:53: server misbehaving
	* Failed to resolve consul-2.consul-svc: lookup consul-2.consul-svc on 100.105.0.3:53: server misbehaving
```

**Comment by adilyse** [comment] 2020-04-01 22:19
Hi @like-inspur,

I'm also seeing these errors in my logs on startup. However, when the agent tries to join the second time, things succeed. Do you see your server pods become ready in Kubernetes eventually?

I'll try to track down where these error logs are coming from, but from what I'm seeing, the servers should eventually work even with these log warning messages.

**Comment by like-inspur** [comment] 2020-04-03 09:45
Hi @adilyse 
When I use above config in server statefulset,  found that pod can't start forever. Because when pod status is not ready, there are no value in service endpoints and no record in dns. But when I delete this readinessProbe config, statefulset pod will start quickly and consul cluster work normally

**Comment by adilyse** [comment] 2020-04-03 20:23
Hmm, okay. The readiness probe for the server statefulset in the Helm chart is as follows:

```
          readinessProbe:
            exec:
              command:
                - "/bin/sh"
                - "-ec"
                - |
                  curl http://127.0.0.1:8500/v1/status/leader \
                  2>/dev/null | grep -E '".+"'
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
```
Have you tried it with this check?

Are you deploying the servers with the Helm chart? If not, have you made other changes to the settings? There might be something else that could be contributing to this behavior.

**Comment by like-inspur** [comment] 2020-04-04 10:12
@adilyse yes, I have config this and don't make other changes to this setting, but found consul server pod start failed. I think if we can config other readinessProbe and add this to livenessProbe

**Comment by ishustava** [comment] 2020-04-10 22:58
Hey @like-inspur, 

The error messages about `server misbehaving` typically mean some sort of DNS misconfiguration. I would suggest searching for this error combined with your Kubernetes provider/setup and try to debug it from there. 

You could confirm by trying to resolve other services from pods on your Kubernetes cluster, like the `kubernetes.default` service. If you're seeing errors resolving it, then the issue is cluster-wide and not-specific to this Helm chart.

If DNS is working correctly, then you would see some DNS resolution errors, as Rebecca mentioned. The errors should like this:
```
    2020-04-10T19:13:44.447Z [WARN]  agent.server.memberlist.lan: memberlist: Failed to resolve iryna-consul-server-2.iryna-consul-server.default.svc: lookup iryna-consul-server-2.iryna-consul-server.default.svc on 10.0.0.10:53: no such host
    2020-04-10T19:13:44.447Z [WARN]  agent: (LAN) couldn't join: number_of_nodes=0 error="3 errors occurred:
	* Failed to resolve iryna-consul-server-0.iryna-consul-server.default.svc: lookup iryna-consul-server-0.iryna-consul-server.default.svc on 10.0.0.10:53: no such host
	* Failed to resolve iryna-consul-server-1.iryna-consul-server.default.svc: lookup iryna-consul-server-1.iryna-consul-server.default.svc on 10.0.0.10:53: no such host
	* Failed to resolve iryna-consul-server-2.iryna-consul-server.default.svc: lookup iryna-consul-server-2.iryna-consul-server.default.svc on 10.0.0.10:53: no such host
```
That is because DNS won't resolve while the pods are initializing. As soon as pods are running, DNS resolution errors would go away and then the cluster should come up.
I don't think we need to change the readiness probes since in this case, they are correctly showing that the cluster is unhealthy.

**Comment by like-inspur** [comment] 2020-04-13 07:16
But on my kubernetes environment, if pod readiness check failed, then there is no record of consul pod in kubernetes dns and no endpoint in consul service, so pod will start failed forever @ishustava

**Comment by lkysow** [comment] 2020-04-13 18:02
@like-inspur are you running normal kubedns or a special dns provider? In my testing kubedns still returns the address even if the readiness check is failing. Are you running Kubernetes in a specific cloud provider?

```
kubectl describe pod consul-server-2|grep Readiness
    Readiness:  exec [/bin/sh -ec curl http://127.0.0.1:8500/v1/atus/leader \
  Warning  Unhealthy  4m2s (x599 over 33m)  kubelet, gke-consul-1-default-pool-51946b93-86rl  Readiness probe failed:
```

```
kubectl exec consul-server-1 -- dig consul-server-2.consul-server.default.svc.cluster.local

; <<>> DiG 9.12.4-P2 <<>> consul-server-2.consul-server.default.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14064
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;consul-server-2.consul-server.default.svc.cluster.local. IN A

;; ANSWER SECTION:
consul-server-2.consul-server.default.svc.cluster.local. 30 IN A 10.32.0.196

;; Query time: 0 msec
;; SERVER: 10.35.240.10#53(10.35.240.10)
;; WHEN: Mon Apr 13 18:02:12 UTC 2020
;; MSG SIZE  rcvd: 89
```

**Comment by like-inspur** [comment] 2020-04-14 06:20
@lkysow I use coredns on my native kubernetes, and coredns version is 1.6.5

**Comment by lkysow** [comment] 2020-04-14 16:32
I've just tested on coredns and I can't replicate. Maybe something is borked with your DNS? Does every other DNS lookup succeed for other servers/statefulsets? Can you try to replicate the readiness probe issue with something other than consul and paste the exact steps?

```
 k describe pod consul-server-2|grep Readiness
    Readiness:      exec [/bin/sh -ec curl \
  Warning  Unhealthy               95s (x22 over 2m38s)  kubelet, ip-192-168-51-191.us-west-2.compute.internal  Readiness probe failed:

kubectl exec consul-server-1 -- dig consul-server-2.consul-server.default.svc.cluster.local


; <<>> DiG 9.12.4-P2 <<>> consul-server-2.consul-server.default.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14972
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 8651d384102c472b (echoed)
;; QUESTION SECTION:
;consul-server-2.consul-server.default.svc.cluster.local. IN A

;; ANSWER SECTION:
consul-server-2.consul-server.default.svc.cluster.local. 5 IN A	192.168.35.174

;; Query time: 0 msec
;; SERVER: 10.100.0.10#53(10.100.0.10)
;; WHEN: Tue Apr 14 16:30:37 UTC 2020
;; MSG SIZE  rcvd: 167
```

**Comment by ishustava** [comment] 2020-06-13 01:09
Hey @like-inspur,

I'm going to close this issue because we weren't able to reproduce. I hope you have resolved the underlying DNS issue.

If you're still seeing problems, please let us know! You could comment here and we will re-open the issue, or create a new issue.

**Closed by ishustava** 2020-06-13 01:09 UTC
Labels: needs-investigation, waiting-on-response
