### ISSUE TITLE
Upgrade Path from 0.24.x w/ existing ACLs is Broken without manual intervention

### ISSUE THREAD

**Issue by shellfu** [hashicorp/consul-helm#767] opened 2021-01-18 16:22 UTC
### Overview of the Issue

Having issues upgrading to 1.9.1 in Kube
Current:

chart 0.24.1
consul 1.8.4

I have tried the chart version listed in the compatibility matrix, using my current values.yaml and modifying the image to 1.9.1 and controller: enabled: true.

At start, the controller and webhook cannot find their secrets.

consul-controller-acl-token not found
consul-connect-inject-acl-token not found

Now, if you set controller: enabled: false, then the upgrade to 0.25.0 will work w/ existing ACLs. However, you cannot upgrade past this point. 

### Reproduction Steps

Build a K8s Consul Cluster using 0.24.1 w/ the below values.yaml file. 

Next, attempt an upgrade to 0.25.0 and enable the controller. The secrets will not be found for the controller or the inject acl.

1. When running helm install with the following `values.yml`:
```
global:
  acls:
   manageSystemACLs: true
   createReplicationToken: true

  enabled: true

  datacenter: dc1

  federation:
    enabled: true
    createFederationSecret: true

  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"

  tls:
    enabled: true
    enableAutoEncrypt: true 
    verify: false
    httpsOnly: true 
    serverAdditionalDNSSANs:
      - "*.consul"
      - "*.svc.cluster.local"
      - "*.int.foobar.net"

controller:
  enabled: true

dns:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: NodePort 

connectInject:
  enabled: true
  aclBindingRuleSelector: "serviceaccount.name!=default"
  # inject an envoy sidecar into every new pod,
  # except for those with annotations that prevent injection
  default: false
  # these settings enable L7 metrics collection and are new in 1.5
  centralConfig:
    enabled: true
    # set the default protocol (can be overwritten with annotations)
    defaultProtocol: 'http'
    # tell envoy where  to send metrics
    proxyDefaults: |
      {
      "envoy_prometheus_bind_addr": "0.0.0.0:9102"
      }

# Configure a Consul client on Kubernetes nodes. GRPC listener is required for Connect.
client:
  grpc: true

server:
  enabled: true
  replicas: 3
  updatePartition: 3
  bootstrapExpect: 3
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  connect: true
  resources:
    requests:
      cpu: "500m"
      memory: "10Gi"
    limits:
      cpu: "500m"
      memory: "10Gi"
  extraConfig: |
    {
      "primary_datacenter": "dc1",
      "performance": {
          "raft_multiplier": 3
      },
      "dns_config": {
        "allow_stale": true,
        "cache_max_age": "10s",
        "enable_additional_node_meta_txt": false,
        "node_ttl": "1m",
        "soa": {
            "expire": 86400, 
            "min_ttl": 30,
            "refresh": 3600,
            "retry": 600
        },
        "use_cache": true
      },
      "telemetry": {
        "prometheus_retention_time": "30s",
        "dogstatsd_addr": "localhost:8125",
        "disable_hostname": true
      }
    }

# Sync Kubernetes and Consul services
syncCatalog:
  enabled: true
  default: true 
  toConsul: true
  toK8S: true
  syncClusterIPServices: true
  nodePortSyncType: ExternalFirst

# Mesh Gateways enable Consul Connect to work across Consul datacenters.
meshGateway:
  enabled: true 
  globalMode: local
  wanAddress:
    source: "Service"
    port: 443
  service:
    enabled: true
    type: LoadBalancer
    port: 443
```

### Expected behavior

I'd expect performing a single upgrade from 0.24.1 to 0.25.0 while following the compatibility matrix would yield any new secrets to be created. I do not see the secrets being checked, created or skipped in the acl-init job. I am not sure if this is an issue with the helm chart here or with consul-k8s.

```
2021-01-18T16:06:50.058Z [INFO]  ACLs already bootstrapped - retrieved bootstrap token from Secret "consul-bootstrap-acl-token"
2021-01-18T16:06:50.446Z [INFO]  Success: calling /agent/self to get datacenter
2021-01-18T16:06:50.446Z [INFO]  Current datacenter: datacenter=dc1
2021-01-18T16:06:50.448Z [INFO]  Policy "agent-token" already exists, updating
2021-01-18T16:06:50.459Z [INFO]  Success: creating agent policy - PUT /v1/acl/policy
2021-01-18T16:06:50.545Z [INFO]  Policy "client-token" already exists, updating
2021-01-18T16:06:50.557Z [INFO]  Success: creating client-token policy
2021-01-18T16:06:50.561Z [INFO]  Secret "consul-client-acl-token" already exists
2021-01-18T16:06:50.563Z [INFO]  Policy "anonymous-token-policy" already exists, updating
2021-01-18T16:06:50.573Z [INFO]  Success: creating anonymous token policy - PUT /v1/acl/policy
2021-01-18T16:06:50.654Z [INFO]  Success: updating anonymous token with policy
2021-01-18T16:06:50.656Z [INFO]  Policy "catalog-sync-token" already exists, updating
2021-01-18T16:06:50.668Z [INFO]  Success: creating catalog-sync-token policy
2021-01-18T16:06:50.672Z [INFO]  Secret "consul-catalog-sync-acl-token" already exists
2021-01-18T16:06:50.677Z [INFO]  Policy "mesh-gateway-token" already exists, updating
2021-01-18T16:06:50.750Z [INFO]  Success: creating mesh-gateway-token policy
2021-01-18T16:06:50.754Z [INFO]  Secret "consul-mesh-gateway-acl-token" already exists
2021-01-18T16:06:50.759Z [INFO]  Success: getting consul-connect-injector-authmethod-svc-account ServiceAccount
2021-01-18T16:06:50.762Z [INFO]  Success: getting consul-connect-injector-authmethod-svc-account-token-g7g92 Secret
2021-01-18T16:06:50.851Z [INFO]  Success: creating auth method consul-k8s-auth-method
2021-01-18T16:06:50.852Z [INFO]  Success: listing binding rules for auth method consul-k8s-auth-method
2021-01-18T16:06:50.861Z [INFO]  Success: updating acl binding rule for consul-k8s-auth-method
2021-01-18T16:06:51.041Z [INFO]  Policy "acl-replication-token" already exists, updating
2021-01-18T16:06:51.241Z [INFO]  Success: creating acl-replication-token policy
2021-01-18T16:06:51.249Z [INFO]  Secret "consul-acl-replication-acl-token" already exists
2021-01-18T16:06:51.249Z [INFO]  server-acl-init completed successfully
```

Notice, the above output is lacking the two secrets in question:

- consul-controller-acl-token 
- consul-connect-inject-acl-token

### Additional Context

The upgrade path from helm chart 0.24.x to even 0.25.0 is broken without manual intervention.

There is simply not a clean upgrade path when you have an existing cluster w/ ACLs already bootstrapped. The only clean way I could upgrade a cluster was when I built a brand new one at 1.8.x on chart 0.24.x and on the upgrade to 0.25 and above I bootstrapped the ACLs there during an upgrade.

An already built cluster with ACLs already in place does not upgrade. I tried many variations using new and old K8s in Digital Ocean.

While some of this can be worked around via manual intervention, this causes a further drift away from the documented upgrade process that will no doubt cause even further problems trying to manage via helm in the future.

**Comment by lkysow** [comment] 2021-01-18 21:59
Hi, sorry for the trouble.

The reason the ACLs aren't being created is because `server.updatePartition` is > 0. This indicates that the servers are being rolled out and so we can't run `server-acl-init` because it won't complete properly while servers are being rolled out and then the job would fail which would cause the whole `helm upgrade` to fail.

So to resolve this situation, please complete [upgrading your servers](https://www.consul.io/docs/k8s/upgrade#upgrading-consul-servers) so that eventually `server.updatePartition` is `0`. Then when you run `helm upgrade` it will run `server-acl-init` and create the necessary ACL tokens and secrets.

**Comment by shellfu** [comment] 2021-01-18 23:23
Thanks for the response. 

Ok, that makes sense. So if I understand you and the documentation you linked correctly, the following needs to happen.

1. Using my existing values.yaml, change the image tag to my desired Consul version (1.9.1 in this case).
2. Run helm upgrade with the current chart and the values.yaml with the new Consul tag until server.updatePartition is 0
3. Proceed with the helm chart upgrade to obtain the controller for use with the new CRDs
4. Document this for myself to prevent future embarrassment :)

Should I be upgrading like 0.24.1 -> 0.25.0 -> 0.26.0 -> 0.27.0 -> 0.28.0?
Or is it permissible to upgrade straight to 0.28.0?

**Comment by shellfu** [comment] 2021-01-19 14:49
In addition to the client's having their update strategy on delete, this should be the same for the mesh gateways as they try to upgrade before the servers do.

**Comment by shellfu** [comment] 2021-01-19 16:08
Ugh. The upgrade caused the servers to start panicking.

```
github.com/hashicorp/go-memdb.(*radixIterator).Next(0xc001e2aba0, 0xc003c9f440, 0x41025aa)
	/go/pkg/mod/github.com/hashicorp/go-memdb@v1.3.0/txn.go:895 +0x2e
github.com/hashicorp/consul/agent/consul/state.cleanupMeshTopology(0x38f5800, 0xc003c9f440, 0x41025aa, 0xc004282d80, 0x41025aa, 0xc004282ef0)
	/home/circleci/project/consul/agent/consul/state/catalog.go:3271 +0x36c
github.com/hashicorp/consul/agent/consul/state.(*Store).deleteServiceTxn(0xc0013d20f0, 0x38f5800, 0xc003c9f440, 0x41025aa, 0xc001e6ecf0, 0x24, 0xc001e11540, 0x47, 0xc004282ef0, 0x0, ...)
	/home/circleci/project/consul/agent/consul/state/catalog.go:1542 +0x8c5
github.com/hashicorp/consul/agent/consul/state.(*Store).deleteNodeTxn(0xc0013d20f0, 0x38f5800, 0xc003c9f440, 0x41025aa, 0xc001e6ecf0, 0x24, 0xb25ddc, 0xc0008c9980)
	/home/circleci/project/consul/agent/consul/state/catalog.go:715 +0x62d
github.com/hashicorp/consul/agent/consul/state.(*Store).DeleteNode(0xc0013d20f0, 0x41025aa, 0xc001e6ecf0, 0x24, 0x0, 0x0)
	/home/circleci/project/consul/agent/consul/state/catalog.go:648 +0xbb
github.com/hashicorp/consul/agent/consul/fsm.(*FSM).applyDeregister(0xc0003fd920, 0xc003c86361, 0x5b, 0x5b, 0x41025aa, 0x0, 0x0)
	/home/circleci/project/consul/agent/consul/fsm/commands_oss.go:171 +0x41a
github.com/hashicorp/consul/agent/consul/fsm.NewFromDeps.func1(0xc003c86361, 0x5b, 0x5b, 0x41025aa, 0xc0004eee20, 0xc00242ad00)
	/home/circleci/project/consul/agent/consul/fsm/fsm.go:99 +0x56
github.com/hashicorp/consul/agent/consul/fsm.(*FSM).Apply(0xc0003fd920, 0xc003c9c690, 0x0, 0x0)
	/home/circleci/project/consul/agent/consul/fsm/fsm.go:133 +0x1b6
github.com/hashicorp/go-raftchunking.(*ChunkingFSM).Apply(0xc001319290, 0xc003c9c690, 0x5191aa0, 0xbff9ded1b226d085)
	/go/pkg/mod/github.com/hashicorp/go-raftchunking@v0.6.1/fsm.go:66 +0x5b
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0025e35d0)
	/go/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:90 +0x2c2
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc00316a000, 0x40, 0x40)
	/go/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc000404f00)
	/go/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:219 +0x3c4
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000404f00, 0xc000ac0080)
	/go/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/go/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:144 +0x66
```

**Comment by shellfu** [comment] 2021-01-19 16:09
Anybody who stumbles upon this, I would HIGHLY advise against performing an upgrade. I have been a Unix Engineer for 15 years and a software developer for 4. 

I consider myself pretty adept and this is not a straight forward process.

**Comment by lkysow** [comment] 2021-01-20 00:16
Hi,
We're really sorry to hear about the upgrade issues.

Unfortunately It looks like you ran into a bug with 1.9.1 that seems the same as https://github.com/hashicorp/consul/issues/9566. This is a top priority for the team and today we worked on a fix (https://github.com/hashicorp/consul/pull/9592). We're going to do a release as soon as possible to fix it (although it sounds like you're back up after a full rebuild).

I know you asked a few other questions so I'll try to answer them for perpetuity even though you've already gone through the upgrade:

> Should I be upgrading like 0.24.1 -> 0.25.0 -> 0.26.0 -> 0.27.0 -> 0.28.0? Or is it permissible to upgrade straight to 0.28.0?

Upgrading directly to 0.28.0 will work. Just make sure to read the changelog and any backwards incompatibilities.

> After performing the upgrade, mesh-gateways never start completely. I see nothing bound to 8443 using netstat -uplate, thus causing the gateway to restart indefinitely.

We'd like to try and reproduce this as it sounds like a bug. This is not the intended behaviour. Which versions were you upgrading between? Was it a Consul version bump from 1.8.7 to 1.9.1 or a Helm upgrade?

> I would suggest performing the upgrade on a cluster you do not have running and supporting active developers. I am trying to find where the delta is that caused the servers to go south, but I unfortunately do not have any more data at this time.

The delta is due to the bug I linked above. We do try to support upgrades in place and unfortunately you ran into a rare panic that's a top priority for us to fix. In general we do recommend upgrading non-production environments before production environments but in this case I don't know if that would have caught the issue and regardless Consul should never panic on an upgrade.

> I would still suggest folks exercise caution and to go through the issues here to determine actions that are not documented

For the list of documentation changes we should add I have:
1. Can you upgrade directly to a specific Helm chart version or should you upgrade one patch release at a time.
2. How to recover from a failed upgrade
3. General guidance on upgrading in place or spinning up a new environment

Is there anything else I'm missing? 

Again, sorry for all the trouble this caused you and your team.

**Comment by shellfu** [comment] 2021-01-20 15:18
> Which versions were you upgrading between? Was it a Consul version bump from 1.8.7 to 1.9.1 or a Helm upgrade?

Starting Consul Version: 1.8.5
Starting Helm Chart: 0.24.1

Target Consul Version: 1.9.1
Target Helm Chart: 0.25.0, 0.26.0

On start, you'd clearly see the mesh gateway attempting to start but the only bound process is the Envoy admin 19000.
On the working gateway, you'd see the process bound to 8443 in addition to the admin port 19000.

The result was the readiness probe was in a constant failing state eventually causing a CrashLoopBackoff. 

The additions I had made to the above values.yaml were image, Imagek8s and imageEnvoy to their latest versions. I rolled back twice and tried the two charts mentioned above with the same result. 

> Is there anything else I'm missing?
1. For a reinstall, the removal of the consul-acl-bootstrap-token must be done to the ACL init fires correctly. Honestly, it would be nice to be able to either 

A) reuse what is there 
B) allow read from Vault _( yeah, not really in the scope but it would be nice )_


> Again, sorry for all the trouble this caused you and your team.

Without puzzles and challenges, our jobs would be pretty boring yeah? Things happen and if I can help provide information/details surrounding issues I've encountered and that leads to someone's day going smoother then that is enough.

I appreciate your time.

**Comment by lkysow** [comment] 2021-01-22 16:38
Can you help me reproduce the mesh gateway bug?

What I tried was upgrading from helm 0.24.0 and values:

<details>
<summary>initial values</summary>

```yaml
global:
  acls:
    manageSystemACLs: true
    createReplicationToken: true

  enabled: true

  datacenter: dc1

  federation:
    enabled: true
    createFederationSecret: true
#
#  gossipEncryption:
#    secretName: "consul-gossip-encryption-key"
#    secretKey: "key"

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: false
    httpsOnly: true
    serverAdditionalDNSSANs:
      - "*.consul"
      - "*.svc.cluster.local"
      - "*.int.foobar.net"

  image: consul:1.8.5

controller:
  enabled: true

dns:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: NodePort

connectInject:
  enabled: true
  aclBindingRuleSelector: "serviceaccount.name!=default"
  # inject an envoy sidecar into every new pod,
  # except for those with annotations that prevent injection
  default: false
  # these settings enable L7 metrics collection and are new in 1.5
  centralConfig:
    enabled: true
    # set the default protocol (can be overwritten with annotations)
    defaultProtocol: 'http'
    # tell envoy where  to send metrics
    proxyDefaults: |
      {
      "envoy_prometheus_bind_addr": "0.0.0.0:9102"
      }

# Configure a Consul client on Kubernetes nodes. GRPC listener is required for Connect.
client:
  grpc: true

server:
  enabled: true
  replicas: 1
#  updatePartition: 3
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  connect: true

# Mesh Gateways enable Consul Connect to work across Consul datacenters.
meshGateway:
  enabled: true
  globalMode: local
  wanAddress:
    source: "Service"
    port: 443
  service:
    enabled: true
    type: LoadBalancer
    port: 443

```

</details>

To Helm 0.26.0:

```
helm upgrade consul hashicorp/consul --version 0.26.0 -f values.yaml --set global.image=consul:1.9.2
```

And the gateways came up:

![upgrade](https://user-images.githubusercontent.com/1034429/105518369-122cc480-5c8d-11eb-9bf6-9cccd5f656ae.gif)

listening on 8443:

```
k exec -it consul-consul-mesh-gateway-55c5c4b9bf-stdwp -- netstat -tlupn
Defaulting container name to mesh-gateway.
Use 'kubectl describe pod/consul-consul-mesh-gateway-55c5c4b9bf-stdwp -n default' to see all of the containers in this pod.
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9102            0.0.0.0:*               LISTEN      1/envoy
tcp        0      0 127.0.0.1:19000         0.0.0.0:*               LISTEN      1/envoy
tcp        0      0 10.32.9.102:8443        0.0.0.0:*               LISTEN      1/envoy
```

Do you remember the state of the Consul clients during the upgrade? I'm wondering if they were unhappy which could cause them to not configure the mesh gateway properly.

**Comment by shellfu** [comment] 2021-01-22 16:45
I will try this again over the weekend and see if I can record steps for reproduction. If it was a ghost then we will find that out also, but I am fairly certain it's reproducible. Just need to get you something concrete.

**Comment by lkysow** [comment] 2021-01-22 16:50
> For a reinstall, the removal of the consul-acl-bootstrap-token must be done to the ACL init fires correctly. Honestly, it would be nice to be able to either
> A) reuse what is there
> B) allow read from Vault ( yeah, not really in the scope but it would be nice )

I've created https://github.com/hashicorp/consul-helm/issues/779 to track A). 

Agreed B) would be great. I've created https://github.com/hashicorp/consul-helm/issues/780 to track.

**Comment by lkysow** [comment] 2021-02-18 20:05
@shellfu did you manage to repro this?

**Comment by lkysow** [comment] 2021-04-09 16:10
I'm going to close this specific ticket because we were unable to reproduce but I can re-open if we hear back.

**Closed by lkysow** 2021-04-09 16:10 UTC
Labels: bug, waiting-on-response
