### ISSUE TITLE
Consul connect ProxyDefaults fails to sync with ExternallyManagedConfigError

### ISSUE THREAD

**Issue by Lysholm** [hashicorp/consul-helm#955] opened 2021-05-18 09:19 UTC
### Overview of the Issue
global ProxyDefault fails to sync

### Reproduction Steps
1. Install consul in a cluster
2. Apply a "ProxyDefaults" manifest

### Logs

```
[x@y scratch]$ kubectl get proxydefaults.consul.hashicorp.com global -n consul -o yaml
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  annotations:
    meta.helm.sh/release-name: sig-consul-config
    meta.helm.sh/release-namespace: consul
  creationTimestamp: "2021-03-25T12:06:53Z"
  finalizers:
  - finalizers.consul.hashicorp.com
  generation: 5
  labels:
    app.kubernetes.io/managed-by: Helm
  name: global
  namespace: consul
  resourceVersion: "57816038"
  selfLink: /apis/consul.hashicorp.com/v1alpha1/namespaces/consul/proxydefaults/global
  uid: 2f66ed1d-6692-41fe-98c4-a573bd8dc5de
spec:
  config:
    envoy_prometheus_bind_addr: 0.0.0.0:9102
    protocol: http
  expose: {}
  meshGateway:
    mode: none
status:
  conditions:
  - lastTransitionTime: "2021-05-14T08:28:35Z"
    message: config entry already exists in Consul
    reason: ExternallyManagedConfigError
    status: "False"
    type: Synced
```

### Expected behavior
proxy defaults sync correctly.

### Environment details

- `consul-k8s` version: same as chart default
- `consul-helm` version: v0.31.1 and v0.32.0-beta2
- `values.yaml` used to deploy the helm chart:

```
global:
  name: consul
  datacenter: otc-cce

  tls:
    enabled: true
    enableAutoEncrypt: true

  federation:
    enabled: true

  acls:
    manageSystemACLs: false

  gossipEncryption:
    secretName: consul-gossip-encryption
    secretKey: key

connectInject:
  enabled: true
  default: true
  centralConfig:
    enabled: true
  healthCheck:
    enabled: true

client:
  enabled: true
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

controller:
  enabled: true

ingressGateways:
  enabled: true
  gateways:
    - name: ingress-gateway
      replicas: 2
      service:
        ports:
        - port: 8080
          nodePort: 32080
        - port: 8443
          nodePort: 32443
        type: NodePort

meshGateway:
  enabled: true
  replicas: 2
  containerPort: 32001
  service:
    port: 32001
    type: NodePort
    nodePort: 32001

terminatingGateways:
  enabled: true

ui:
  enabled: true
  service:
    enabled: true
    type: ClusterIP

syncCatalog:
  enabled: true
  default: true
  toConsul: true
  toK8S: false

server:
  replicas: 3
  storage: 1Gi
  storageClass: csi-nas
  extraConfig: |
    {
      "log_level": "DEBUG",
      "translate_wan_addrs": true
    }
```

- Cloud Provider: Open Telekom Cloud
- Networking CNI plugin in use: Canal (i think that's what it's called, the one provided by huawei cloud container engine in any case)

**Comment by ndhanushkodi** [comment] 2021-05-18 18:51
hey @Lysholm can you try your reproduction steps again and before applying the proxydefaults CRD, run `consul config list -kind proxy-defaults` against the consul server? Just to make sure a config entry isn't being applied outside of the CRDs, since the error message says: `config entry already exists in Consul`. Are there any pipelines/automation that might be adding config entries outside of the CRD you are applying?

**Comment by lkysow** [comment] 2021-05-20 21:17
You may also find https://www.consul.io/docs/k8s/crds/upgrade-to-crds#migrating-config-entries useful for migrating to a CRD once you've confirmed there are no outside pipelines/automation setting these config entries.

**Comment by david-yu** [comment] 2021-06-25 18:15
Closing for now, if you have more details you'd like share please re-open, we have provided some details on migrating CRDs.

**Closed by david-yu** 2021-06-25 18:15 UTC
Labels: bug, waiting-on-response
