### ISSUE TITLE
how to add health check for synced service

### ISSUE THREAD

**Issue by webliupeng** [hashicorp/consul-helm#131] opened 2019-03-11 06:24 UTC
I'm new to consul.
I have installed consul in k8s(version:1.10) with helm chart(master branch) . enabled catalog sync .  There is no any healthy service. And all synced services in a same node, name is k8s-sync, the node no any health check. ip address is 127.0.0.1

My questions are:

- how to add health check for this node?
- why k8s-sync node ip address is 127.0.0.1.something wrong?

**Comment by peidong-hu** [comment] 2019-06-25 18:17
got same question, all the synced services from k8s to consul have no health check

**Comment by lkysow** [comment] 2019-10-31 21:43
Hi @webliupeng I'll try to answer your questions one by one.

> There is no any healthy service.

There should be services synced into Consul from Kubernetes:
![image](https://user-images.githubusercontent.com/1034429/67987682-441abc80-fbeb-11e9-9c27-7af233bd46c3.png)

They don't have any health checks so they shouldn't be unhealthy. Can you explain what you mean by this?

> And all synced services in a same node, name is k8s-sync, the node no any health check.

The sync works differently than the way services are usually registered into Consul. Because some [service types](https://www.consul.io/docs/platform/k8s/service-sync.html#kubernetes-service-types) don't result in syncing each individual Pod to Consul, we can't rely on there always being a "node" for each service instance to be on. Instead, we create a "fake" node called k8s-sync to register the services on. This node has no health checks because it's not a real node.

> ip address is 127.0.0.1

Because `k8s-sync` is not a real node, we just make up an IP for it. This IP isn't used for anything because each service has its own IP.

Regarding health checks in general. Currently there's no way to add health checks to the service that's synced from Kubernetes. Kubernetes health checking will still work to ensure you're not routing to unhealthy services, however you currently can't view the service status in Consul.
* If `NodePort` then we register NodeIPs and node port. When your request reaches the node, the kube-proxy will ensure it's routed to a Pod that's healthy
* If `LoadBalancer` then it's the same as above since after passing through the LoadBalancer you'll hit a NodePort
* If `ExternalIP` then we route directly to it without health checking however Kubernetes doesn't do any health checking either
* If `ClusterIP` then it's only routable via a kube-proxy which will take the health of services into account

**Comment by lkysow** [comment] 2019-10-31 21:47
I'm going to close this as a duplicate of https://github.com/hashicorp/consul-k8s/issues/29 where we'll be tracking the ability to add health checks to synced services.

If you have any more questions let us know. Thanks!

**Closed** 2019-10-31 21:47 UTC
Labels: duplicate, question, theme/health-checks

**Comment by webliupeng** [comment] 2019-11-01 07:35
Thanks for your answer. It's very clear. @lkysow
