### ISSUE TITLE
Failed helm upgrade leaves behind a job that prevents future upgrades?

### ISSUE THREAD

**Issue by TJM** [hashicorp/consul-helm#986] opened 2021-06-10 15:29 UTC
#### Question

Please provide as many details as you can, including but not limited to
- Helm command you're running - We are using terraform to apply the helm

```hcl
resource "helm_release" "consul" {
  provider         = helm.services
  name             = "consul"
  namespace        = kubernetes_namespace.consul.metadata.0.name
  repository       = "https://helm.releases.hashicorp.com"
  chart            = "consul"
  version          = "0.31.1"
  create_namespace = "false"
  max_history      = 10

  values = [
    <<-EOT
    global:
      image: "hashicorp/consul-enterprise:1.9.5-ent"
      datacenter: "us-central1"
      acls:
        manageSystemACLs: true
      tls:
        enabled: true
        enableAutoEncrypt: true
        verify: true
        httpsOnly: true
    server:
      enterpriseLicense:
        secretName: ${kubernetes_secret.consul_enterprise_license.metadata.0.name}
        secretKey: license-key
    ui:
      service:
        annotations: | # https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#service_annotations_related_to_ingress
          cloud.google.com/app-protocols: '{"https":"HTTPS","http":"HTTP"}'
      ingress:
        annotations: | # https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#ingress_annotations
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: ${google_compute_global_address.consul.name}
          ingress.gcp.kubernetes.io/pre-shared-cert: ${google_compute_ssl_certificate.consul.name}
          kubernetes.io/ingress.allow-http: "false"
        enabled: true
        hosts:
          - host: consul.gcp.domain.com
            paths:
              - /
        tls:
          - hosts:
              - consul.gcp.domain.com

    EOT
  ]

  depends_on = [
    google_container_cluster.services,
    google_container_node_pool.services_node_pool_1,
    google_compute_ssl_certificate.consul,
    google_compute_global_address.consul,
  ]
}
```

... effectively it would be `helm upgrade consul hashicorp/consul -f values.yaml`

- Any values you've configured

```
$ helm get values consul
USER-SUPPLIED VALUES:
global:
  acls:
    manageSystemACLs: true
  datacenter: us-central1
  image: hashicorp/consul-enterprise:1.9.5-ent
  tls:
    enableAutoEncrypt: true
    enabled: true
    httpsOnly: true
    verify: true
server:
  enterpriseLicense:
    secretKey: license-key
    secretName: consul-enterprise-license
ui:
  ingress:
    annotations: |
      kubernetes.io/ingress.class: gce
      kubernetes.io/ingress.global-static-ip-name: global-consul-ip
      ingress.gcp.kubernetes.io/pre-shared-cert: consul-certificate-20210609213232702600000001
      kubernetes.io/ingress.allow-http: "false"
    enabled: true
    hosts:
    - host: consul.gcp.domain.com
      paths:
      - /
    tls:
    - hosts:
      - consul.gcp.domain.com
  service:
    annotations: |
      cloud.google.com/app-protocols: '{"https":"HTTPS","http":"HTTP"}'
```

- Your current understanding, and what you're trying to figure out

* Consul was installed without an "ingress" because we were trying to decide which ingress type to use
* I added the ingress information (from `ui:` down) in the values
* The first upgrade gave me an error:

```
Upgrade "consul" failed: post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook consul/templates/enterprise-license-job.yaml: unable to recognize "": Get "https://34.70.X.X/api?timeout=32s": dial tcp 34.70.X.X:443: i/o timeout
```

NOTE: IP address is the GKE API server.. not sure exactly what is going on here, it looks like the helm chart is trying to connect to the API server from the worker nodes? Can anyone confirm?

* Then on subsequent retries, I get this error:

```
Upgrade "consul" failed: post-upgrade hooks failed: warning: Hook post-upgrade consul/templates/server-acl-init-cleanup-job.yaml failed: jobs.batch "consul-consul-server-acl-init-cleanup" already exists
```

We have, however been able to apply other changes, such as enabling audit logging, without an issue. I think it is something specific to adding an ingress, and maybe that "job" is causing me issues?

Thanks in advance,
Tommy

**Comment by lkysow** [comment] 2021-06-10 18:21
Hi @TJM,
This is an unfortunate limitation of Helm. I think that what happened is that Helm briefly lost network communication between where Terraform is running and the kube api server. It then couldn't delete the `server-acl-init-cleanup` Job which it would do normally after an upgrade.

At this point, you'll need to manually delete the job and probably the serviceaccount, clusterrole, etc. before you can do any further upgrades.

**Comment by TJM** [comment] 2021-06-10 19:17
@lkysow This happens every time, predictably in the same place (`enterprise-license-job.yaml`) . We have our terraform pipelines setup in such a way that we can completely rebuild the cluster and re-try the pipeline. It does not appear to be a "temporary" or fluke event. However, we have been doing some additional testing and found that when we set the ui.ingress.enabled = false, it succeeds, back to true and it fails. So, even though there are no signs of Values.ui.ingress.enabled outside its own template, there is something funky going on there.

We are doing some additional testing. I am fairly sure that my values are the problem.

**Comment by lkysow** [comment] 2021-06-10 22:14
Ahh okay. I just tried this out with your values and I couldn't reproduce the issue, at least using `helm` directly.

Can you reproduce using `helm upgrade <release name> hashicorp/consul -f <values.yaml>`?

**Comment by TJM** [comment] 2021-06-10 22:16
I am pretty sure its a combination of several things...

* It has to be an "upgrade" (change of values)
* GKE
* Terraform (it has to be terraform helm provider with that weird timeout=32s?)

I am still not sure it isn't some silly company default network policy thing. Maybe something that prevents the nodes from communicating to the Kubernetes API? :D

**Comment by TJM** [comment] 2021-06-10 23:49
It appears to be an issue with the following annotation:
```
      ingress.gcp.kubernetes.io/pre-shared-cert: consul-certificate-20210609213232702600000001
```
... I have yet to get a *valid* error from it, but when I switched from "pre-shared certificates" to K8s "secret" based, it worked fine (shrug). Now, I have problems with the "custom" readiness probes, but thats another issue :)

**Comment by david-yu** [comment] 2021-06-29 21:50
Hi @TJM thanks for following up. I'll go ahead and close, but feel free to re-open if there is an issue that needs to be addressed in Consul K8s.

**Closed by david-yu** 2021-06-29 21:50 UTC
Labels: question, waiting-on-response

**Comment by TJM** [comment] 2021-06-29 22:31
No need to re-open, but we found the problem was due to a workaround that was put in place for the helm provider authentication. We switched that over to use a TF VAR for the token instead of "exec" to generate a token and magically things started working as expected.

Thanks
