### ISSUE TITLE
Consul pods will not turn on after restarting all of Kubernetse(EKS) nodes 

### ISSUE THREAD

**Issue by msidd111** [hashicorp/consul-helm#240] opened 2019-10-04 15:13 UTC
One of resilience use case for consul that I tested was to restart all of nodes of Kubernetes cluster. Aws EKS will restart all nodes fine but one of consul node will stuck in pending state and other two will stay in not ready state so all of consul nodes becomes unavilable.
 
Here is events logs of pod with pending state.
```
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  37m (x2 over 37m)   default-scheduler  0/2 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 1 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  36m (x6 over 36m)   default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 1 node(s) had taints that the pod didn't tolerate, 1 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  95s (x44 over 36m)  default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) had volume node affinity conflict.
```

Here is full log of pod with pending state 
```
kubectl describe pod doltish-bird-consul-server-2
Name:               doltish-bird-consul-server-2
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app=consul
                    chart=consul-helm
                    component=server
                    controller-revision-hash=doltish-bird-consul-server-6c4df94c65
                    hasDNS=true
                    release=doltish-bird
                    statefulset.kubernetes.io/pod-name=doltish-bird-consul-server-2
Annotations:        consul.hashicorp.com/connect-inject: false
                    kubernetes.io/psp: eks.privileged
Status:             Pending
IP:
Controlled By:      StatefulSet/doltish-bird-consul-server
Containers:
  consul:
    Image:       consul:1.5.0
    Ports:       8500/TCP, 8301/TCP, 8302/TCP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP
    Command:
      /bin/sh
      -ec
      CONSUL_FULLNAME="doltish-bird-consul"

      exec /bin/consul agent \
        -advertise="${POD_IP}" \
        -bind=0.0.0.0 \
        -bootstrap-expect=3 \
        -client=0.0.0.0 \
        -config-dir=/consul/config \
        -datacenter=dc1 \
        -data-dir=/consul/data \
        -domain=consul \
        -hcl="connect { enabled = true }" \
        -ui \
        -retry-join=${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
        -retry-join=${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
        -retry-join=${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
        -server

    Readiness:  exec [/bin/sh -ec curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
grep -E '".+"'
] delay=5s timeout=5s period=3s #success=1 #failure=2
    Environment:
      POD_IP:      (v1:status.podIP)
      NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /consul/config from config (rw)
      /consul/data from data-default (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from doltish-bird-consul-server-token-bcwqj (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data-default:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-default-doltish-bird-consul-server-2
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      doltish-bird-consul-server-config
    Optional:  false
  doltish-bird-consul-server-token-bcwqj:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  doltish-bird-consul-server-token-bcwqj
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  37m (x2 over 37m)   default-scheduler  0/2 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 1 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  36m (x6 over 36m)   default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 1 node(s) had taints that the pod didn't tolerate, 1 node(s) had volume node affinity conflict.
  Warning  FailedScheduling  95s (x44 over 36m)  default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) had volume node affinity conflict.
```

Logs for other pods are attached. 
![pods_status](https://user-images.githubusercontent.com/13205188/66218802-f10b2380-e697-11e9-925c-91dedf931eda.PNG)

[doltish-bird-consul-server-1_logs.txt](https://github.com/hashicorp/consul-helm/files/3691134/doltish-bird-consul-server-1_logs.txt)
[doltish-bird-consul-server-0_logs.txt](https://github.com/hashicorp/consul-helm/files/3691135/doltish-bird-consul-server-0_logs.txt)

**Comment by lkysow** [comment] 2019-10-29 20:17
I think this is a duplicate of https://github.com/hashicorp/consul-helm/issues/243

**Closed by lkysow** 2019-10-29 20:17 UTC
Labels: needs-investigation, question
