### ISSUE TITLE
Consul Inject Init Container resolving incorrect IP in Azure AKS version 1.19.3 

### ISSUE THREAD

**Issue by broomyocymru** [hashicorp/consul-helm#751] opened 2020-12-21 08:58 UTC
Following an upgrade of our worker nodes to Kubernetes 1.19.3 the inject init container fails to start as it resolves the IP of the node not the virtual IP of the consul service.  All other consul containers seem to start-up without issues.

The error message is:
Error registering service "<app-name>": Put "http://<node-ip>:8500/v1/agent/service/register": dial tcp <node-ip>:8500: connect: connection refused.

Previously this would resolve to the Consul Service cluster IP in Kubernetes. We've tried exposing the service as a load balancer but the node IP is still called by the container. We initially had the issue the using Helm chart version 0.26.0 with Consul 1.8. We have since upgraded to 0.27.0  and 1.9.0 but the issue is the same.

**Comment by ishustava** [comment] 2020-12-21 17:42
Hey @broomyocymru,

The init container that the connect webhook injects has always been talking to the [host IP](https://github.com/hashicorp/consul-k8s/blob/00bbbb67a85b33559f689ecad2c029d26dbc0d02/connect-inject/container_init.go#L247) rather than a cluster IP of the consul service. It actually talks to the Consul client agent on its host, that's why it's using host IP. 

It looks like in your case, the host IP is not resolving for some reason, that is the env variable is empty or not set. I'm not sure how it could happen. We have acceptance tests that have been running against AKS 1.19.3, and we have not observed this issue. 

Could you try to come up with reproducible steps for us?

**Comment by broomyocymru** [comment] 2021-01-05 09:43
Hey @ishustava ,
Our configuration uses AKS with Private Link and custom DNS. That being said this wasn't an issue previously on the lower AKS version. Do you have a test setup in this configuration?

**Comment by lkysow** [comment] 2021-01-05 21:46
@broomyocymru this may be an issue with the Kubernetes downward API in this configuration. Can you run this pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: downward-debug
spec:
  containers:
    - name: downard-debug
      image: tutum/curl:latest
      env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "echo hostip: \"$HOST_IP\"; echo; while true; do sleep 30; done;" ]
```

And paste the output of `kubectl logs downward-debug`?

**Comment by broomyocymru** [comment] 2021-01-06 11:22
@lkysow the output is the IP of the node (i've escaped it)
hostip: -- x.103.x.x --

But pod ip range is x.244.x.x and this is what the consul agents on each node are registered with in consul server. 

I've also noticed the azure subnets route table has entries for each node (AKS created) where anything in the range x.244.y.x/24 has a next hop of x.103.x.x. I'm not sure if this has always been the case with AKS but I don't have another cluster to check.

**Comment by lkysow** [comment] 2021-01-06 18:29
The consul client register themselves with their pod IPs but each service mesh app uses its local node IP to talk to its local consul client through the exposed host port. The application pods must be able to make a connection through that node IP to the local consul client on port 8500 (tls disabled) or port 8501 (tls enabled).

You can't put up a LB in front of anything because the connect app __must__ talk to its local Consul client on that node.

So I think we need to figure out why that connection isn't working.

**Comment by lkysow** [comment] 2021-02-18 20:05
This might actually have been an AKS bug (https://github.com/Azure/AKS/issues/2070). This is now fixed so I'm going to close this.

**Closed by lkysow** 2021-02-18 20:05 UTC
Labels: area/connect, bug, waiting-on-response
