### ISSUE TITLE
Consul client not getting launched on all the nodes

### ISSUE THREAD

**Issue by hussainsaify** [hashicorp/consul-helm#668] opened 2020-10-28 12:45 UTC
Hi Team,

We have upgraded consul chart to 0.25.0 version but after the chart upgrade, some of the client pods are not getting launched and are in a pending state. This is happening because the server and clients are both using the same ports and the server is already launched on that node.

Is this a bug? Ideally, client pods should not be launched to that node.

Cluster- AWS EKS 
K8s Version - 1.18
Chart version- 0.25.0

Here is the event from the pod that is in pending state

Events:
  Type     Reason             Age                        From                Message
  ----     ------             ----                       ----                -------
  Warning  FailedScheduling   2m45s (x2 over 2m45s)      default-scheduler   0/17 nodes are available: 13 node(s) didn't have free ports for the requested pod ports, 4 Insufficient cpu.
  Normal   NotTriggerScaleUp  2m37s                      cluster-autoscaler  pod didn't trigger scale-up (it wouldn't fit if a new node is added): 6 node(s) didn't have free ports for the requested pod ports, 3 node(s) didn't match node selector
  **Warning  FailedScheduling   <invalid> (x6 over 2m42s)  default-scheduler   0/17 nodes are available: 12 node(s) didn't have free ports for the requested pod ports, 5 Insufficient cpu.**

Please let me know if I am making some mistake or is this a bug?

Thanks,
Hussain

**Comment by lkysow** [comment] 2020-10-28 18:12
Hi, the servers and clients don't share the same ports unless you have something special in your config? Servers don't use any `hostPorts` so there should be no issue there. Clients use 8500 (or 8501 if tls is enabled) and 8502.

**Comment by hussainsaify** [comment] 2020-10-29 01:09
Hi,

I am seeing that server and clients have common ports configured. Also, attaching the helm values file.

Server-

   consul:
    Image:       consul:1.8.4
    Ports:       8500/TCP, 8301/TCP, 8302/TCP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP


Client-

  consul:
    Image:       consul:1.8.4
    Ports:       8500/TCP, 8502/TCP, 8301/TCP, 8301/UDP, 8302/TCP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  8500/TCP, 8502/TCP, 0/TCP, 0/UDP, 0/TCP, 0/TCP, 0/TCP, 0/UDP
[consul-values.txt](https://github.com/hashicorp/consul-helm/files/5455568/consul-values.txt)

**Comment by lkysow** [comment] 2020-10-29 23:18
The ports set to 0 mean there's not a host port for any of those ports.
```
Host Ports: 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP
```

I think the issue isn't ports and may be due to not enough CPU on those nodes.

**Comment by lkysow** [comment] 2020-12-01 03:05
Hi, we're going to close this one for now but if there are still issues please let us know and we'll be happy to re-open.

**Closed by lkysow** 2020-12-01 03:05 UTC
Labels: question, waiting-on-response
