### ISSUE TITLE
[Question] Run agent as deployment 

### ISSUE THREAD

**Issue by ltagliamonte-dd** [hashicorp/consul-helm#640] opened 2020-10-09 18:23 UTC
For HA reason we run the cluster coreDNS in our k8s cluster as daemonset and deployment, this setup is working really great for us especially during updates.

Current Consul installation supports only daemonset, would love to understand if is technically possible to run consul in agent mode without serf,telemetry,memeberlist basically just as "connected" DNS resolver.

In general having serf, memberlist, and telemetry off in kubernetes where pods IPs do no match with servers IP would tremendously reduce load on the cluster.
K8s clusters can span over thousand of servers (like ours) and there is a lot of overhead that could be removed imho.

**Comment by lkysow** [comment] 2020-10-13 16:49
This question is a duplicate of one in Discuss which I've answered (https://discuss.hashicorp.com/t/question-run-consul-agent-as-deployment-in-k8s/15523/2) so I'm going to close this.

**Closed by lkysow** 2020-10-13 16:49 UTC
Labels: question
