### ISSUE TITLE
/v1/operator/keyring api doesn't work after `helm upgrade`

### ISSUE THREAD

**Issue by soonoo** [hashicorp/consul-helm#898] opened 2021-04-07 15:25 UTC
### Reproduction Steps
1. There is no problem with freshly installed consul cluster.
2. Following [Upgrading Consul Server](https://www.consul.io/docs/k8s/upgrade#upgrading-consul-servers) guide, I upgraded one conser-server of three.
3. After upgrade, `/v1/operator/keyring` endpoint returns below message. It seems something token/key related is wrong with upgraded consul-server 
```
$ curl consul.ingress.domain/v1/operator/keyring
1 error occurred:
	* WAN error: 2/3 nodes reported success
```

There are three consul servers. (`consul-server-0`, `consul-server-1`, `consul-server-2`) 
**Upgraded** consul-server's(`consul-server-2`) log:
```
2021-04-07T15:17:27.602Z [WARN] agent.server.memberlist.lan: memberlist: Was able to connect to dev-worker-1 but other probes failed, network may be misconfigured
2021-04-07T15:17:27.902Z [WARN] agent.server.memberlist.lan: memberlist: Was able to connect to dev-worker-11 but other probes failed, network may be misconfigured
2021-04-07T15:17:32.895Z [WARN] agent.server.memberlist.wan: memberlist: Was able to connect to consul-server-0.groot-k8s but other probes failed, network may be misconfigured
2021-04-07T15:17:37.895Z [WARN] agent.server.memberlist.wan: memberlist: Was able to connect to consul-server-1.groot-k8s but other probes failed, network may be misconfigured
...
```

Other consul-servers\` (`consul-server-0`, `consul-server-1`) log:
```
2021-04-07T15:18:41.425Z [WARN] agent.server.memberlist.wan: memberlist: Was able to connect to consul-server-2.k8s but other probes failed, network may be misconfigured
2021-04-07T15:18:46.425Z [WARN] agent.server.memberlist.wan: memberlist: Was able to connect to consul-server-2.k8s but other probes failed, network may be misconfigured
2021-04-07T15:18:56.425Z [WARN] agent.server.memberlist.wan: memberlist: Was able to connect to consul-server-2.k8s but other probes failed, network may be misconfigured
2021-04-07T15:19:06.425Z [WARN] agent.server.memberlist.wan: memberlist: Was able to connect to consul-server-2.k8s but other probes failed, network may be misconfigured
```

values.yml:
```
global:
  datacenter: Groot-k8s
  name: consul
  domain: search
  image: consul:1.9.4
  acls:
    manageSystemACLs: true
  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

server:
  enabled: true
  exposeGossipAndRPCPorts: true
  replicas: 3
  bootstrapExpect: 3
  ports:
    serflan:
      port: 9301

client:
  enabled: true
  exposeGossipPorts: true

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  addK8SNamespaceSuffix: false

ui:
  enabled: true
  service:
    type: NodePort
```

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: 0.25.0
- `consul-helm` version: 0.31.1

Additionally, please provide details regarding the Kubernetes Infrastructure, if known:
- Cloud Provider (If self-hosted, the Kubernetes provider utilized): self hosted
- Networking CNI plugin in use: cilium

**Comment by lkysow** [comment] 2021-04-08 00:52
Hi, unfortunately I'm not able to reproduce this on GKE. It may due to the Kubernetes version or cilium. Can you verify that when you run `kubectl get pod -o yaml` for each upgraded server pod that all the ports are defined with udp and tcp as expected:


```yaml
ports:
    - containerPort: 8500
      name: http
      protocol: TCP
    - containerPort: 9301
      hostPort: 9301
      name: serflan-tcp
      protocol: TCP
    - containerPort: 9301
      hostPort: 9301
      name: serflan-udp
      protocol: UDP
    - containerPort: 8302
      hostPort: 8302
      name: serfwan-tcp
      protocol: TCP
    - containerPort: 8302
      hostPort: 8302
      name: serfwan-udp
      protocol: UDP
    - containerPort: 8300
      hostPort: 8300
      name: server
      protocol: TCP
    - containerPort: 8600
      name: dns-tcp
      protocol: TCP
    - containerPort: 8600
      name: dns-udp
      protocol: UDP
```


My instinct is that this is due to a) some issues where Kubernetes isn't supporting both UDP and TCP on the same port or b) cilium isn't supporting it. The errors you're getting are due to udp packets not working. Consul will actually fall back to tcp without issue FYI. What I'm not sure of is why it worked on initial install but not upgrade. We did see some issues were the upgrade didn't patch the statefulset and pods properly so that's why I'd like to see your pod yaml output.

**Comment by soonoo** [comment] 2021-04-08 15:35
@lkysow Thank you so much for checking.
The same settings are applied to all consul servers. 

The nodes themselves seem to support both TCP and UDP, by the way:

### hostport-sample.yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostport
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: http
      hostPort: 9901
      containerPort: 80
      protocol: TCP
  - name: dns-server
    image: sameersbn/bind  # simple dns server image
    ports:
    - name: udp
      hostPort: 9901
      containerPort: 53
      protocol: UDP
```
After applying above yaml file,

1. TCP test
```
$ curl http://k8s-worker-node1.domain:9901
<!DOCTYPE html>
<html>
<head>
```


2. UDP test
```
$ nslookup abc.com k8s-worker-node1.domain -port=9901
Server:		k8s-node.domain
Address:	10.111.34.44#9902
```


Can you tell me if there's a command like `consul agent ping consul-server-2.k8s -p 8302`?
Thank you again for the answer.

**Comment by lkysow** [comment] 2021-04-08 21:13
Can you try the same test but with the ports on the same container and both the hostPort and containerPort the same?

```yaml
    - containerPort: 9301
      hostPort: 9301
      name: serflan-udp
      protocol: UDP
    - containerPort: 8302
      hostPort: 8302
      name: serfwan-tcp
      protocol: TCP
```

> Can you tell me if there's a command like consul agent ping consul-server-2.k8s -p 8302?

No, but you could use `nc`, e.g.
```
nc -v -u -z -w 3 <consul node IP> 9301
```

**Comment by soonoo** [comment] 2021-04-25 17:20
I did simple test in each consul-server container and it seems all necessary ports/protocol are open between servers.
```bash
$ nc <consul node IP> 8302 -vzu
<IP> (<IP>:8302) open

$ nc <consul node IP> 8302 -vz
<IP> (<IP>:8302) open

$ nc <consul node IP> 9301 -vzu
<IP> (<IP>:9301) open

$ nc <consul node IP> 9301 -vz
<IP> (<IP>:9301) open
```

I'm still checking, but I don't know what to do. Thank you for letting me know and I'll leave a comment if something is found.

**Comment by david-yu** [comment] 2021-06-26 01:52
Hi @soonoo could you try with the latest version of the Helm chart and Consul 1.10? Does the issue still persist? I also assume you are using the latest version of Cilium that supports host port?

**Comment by soonoo** [comment] 2021-07-10 18:01
Hi @david-yu. Sorry for the late reply.
After installing consul on a new k8s cluster the issue went away. (with `consul:1.9.4` and `chart release 0.31.1`)
I think the problem was with the old k8s cluster's network, not the consul.

**Comment by david-yu** [comment] 2021-07-12 16:19
Ok thanks for getting back to us @soonoo. Will close this issue!

**Closed by david-yu** 2021-07-12 16:19 UTC
Labels: bug, needs-investigation, theme/upgrades, waiting-on-response
