### ISSUE TITLE
ACL not show Token

### ISSUE THREAD

**Issue by cristhianbicca** [hashicorp/consul-helm#209] opened 2019-08-02 16:53 UTC
Good morning guys, I'm deploying consul as a service discovery on my Kubernetes framework and trying to enable ACL he's asking for a SecretID or Master Token, but what I got from Kubernetes Secret didn't work out. Where can I get this token?

versions
Consul server - 1.5.0
consul-helm 0.9

**Comment by lkysow** [comment] 2019-09-17 17:19
Hi @cristhianbicca I think this is a duplicate of #218, looks like we both created issues 😄.

I think I've answered your question there so I'm going to close this.

**Closed by lkysow** 2019-09-17 17:19 UTC
