### ISSUE TITLE
Expose Consul DNS outside of Kubernetes cluster

### ISSUE THREAD

**Issue by iridian-ks** [hashicorp/consul-helm#362] opened 2020-02-27 01:03 UTC
Hello,

I did some searches to try and figure if someone else is trying to do the same thing as me. I'm somewhat new to Consul so I apologize if this is a bad question.

I had the idea to expose NodePorts to the network by leveraging Consul's kubernetes sync. I got Services to sync, but now I need some DNS, which defaults to `name.service.consul`. What I was thinking we could do would be to leverage our existing DNS and have Consul own a subdomain.

Assuming we owned `example.com` then something like: `consul.example.com` so that the service was accessible from `name.service.consul.example.com`. This would require the DNS ports to be open so that I could point some records to it.

Right now, it seems the DNS ports aren't open and I can't see other issues on this so I feel like I'm not doing something right?

Am I going about this the wrong way?

Thanks in advance!

**Comment by lkysow** [comment] 2020-02-27 14:29
Hi, port 8600 is open: https://github.com/hashicorp/consul-helm/blob/master/templates/server-statefulset.yaml#L194

Can you make sure you're using this chart and not the one in helm/stable?

We have docs on Consul DNS here: https://www.consul.io/docs/platform/k8s/dns.html. Does than help?

**Comment by iridian-ks** [comment] 2020-02-28 23:16
Hi @lkysow thanks for the response.

So, I'm looking here: https://github.com/hashicorp/consul-helm/blob/master/templates/client-daemonset.yaml#L210

The Consul port is using hostPort, which exposes it outside the cluster. I meant to say that I'd like to access Consul's DNS from services outside the Cluster.

**Comment by lkysow** [comment] 2020-03-02 15:09
Ahh okay I understand. Have you tried creating a Kubernetes LoadBalancer service that points at the servers or clients on port 8600 and uses UDP protocol. I think that would be the "kubernetes way" for solving this.

**Comment by iridian-ks** [comment] 2020-03-13 18:12
Sure, I could do that. Ideally, it's part of the chart, even if it's optional.

**Comment by adilyse** [comment] 2020-04-03 20:27
Hi @iridian-ks,

Can you clarify what you mean by "exposing [dns] outside the cluster"? Would you like it to be available on the public internet? Or available outside of the Kubernetes cluster but still within a trusted, internal datacenter?

Thanks!

**Comment by iridian-ks** [comment] 2020-04-05 17:32
Hi @adilyse , definitely not on the public internet. Just external to the cluster for other internal services where we don't want to or can't install consul agents.

**Comment by david-yu** [comment] 2021-05-25 22:09
Closing as this is a duplicate of https://github.com/hashicorp/consul-helm/issues/659

**Closed by david-yu** 2021-05-25 22:09 UTC
Labels: area/dns, area/sync, enhancement
