### ISSUE TITLE
wrong type for value; expected string; got map[string]interface {}

### ISSUE THREAD

**Issue by metanovii** [hashicorp/consul-helm#602] opened 2020-09-11 15:56 UTC
helm chart v 0.24.1
helm 3.3.1

values:
```
server:
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"
```

```
╰─ helm upgrade --install ./consul -f custom-values-consul.yaml          
                                                                                                                                                            
Release "hashicorp-consul" does not exist. Installing it now.
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value <nil>
coalesce.go:199: warning: destination for resources is a table. Ignoring non-table value requests:
  memory: "128Mi"
  cpu: "250m"
limits:
  memory: "256Mi"
  cpu: "500m"
Error: template: consul/templates/server-statefulset.yaml:262:26: executing "consul/templates/server-statefulset.yaml" at <.Values.server.resources>: wrong type for value; expected string; got map[string]interface {}
```

**Comment by lkysow** [comment] 2020-09-11 16:01
Hi, I think this is a duplicate of https://github.com/hashicorp/consul-helm/issues/486#issuecomment-642134203.

I'm guessing your `custom-values-consul.yaml` has all of the possible values and you've taken that from `master`? Instead your custom-values file should only set the keys that you're overriding, e.g. if you're only switching `connectInject.enabled=true` then it should only contain:
```
connectInject:
  enabled: true
```

**Comment by metanovii** [comment] 2020-09-11 16:53
Yep, custom-values-consul.yaml has all values.
 I try with default vault.yaml:
helm upgrade --install ./consul -f consul/vault.yaml  - error
but
helm upgrade --install ./consul  - ok  

Some kind of magic :D

**Closed** 2020-09-11 16:59 UTC
Labels: duplicate, question, waiting-on-response
