### ISSUE TITLE
Acl-token Permission denied

### ISSUE THREAD

**Issue by jiangyongbing24** [hashicorp/consul-helm#359] opened 2020-02-25 03:15 UTC
I use the token in acl-tokens.json to access consul-ui normally, but I use this token in spring cloud consul to register my service, and the prompt message: Permission Denied. Isn't this token a bootstrap acl token? How do I get a token with sufficient permissions?

**Comment by lkysow** [comment] 2020-02-25 19:43
Hi, I think this is a duplicate of https://github.com/hashicorp/consul-helm/issues/360?

**Comment by lkysow** [comment] 2020-02-26 16:35
Closing as duplicate

**Closed by lkysow** 2020-02-26 16:35 UTC
Labels: duplicate, question
